### ISSUE TITLE
Run script for linux

### ISSUE THREAD

**Issue by JefvdA** [Robby-cell/terminal-hangman#3]
Hi there!

I was browsing through some github repo's and came across this one. I saw you created a [script](https://github.com/Robby-cell/terminal-hangman/blob/main/hangman.bat) to start up the application.

Simple suggestion: add a `hangman.sh` file for the linux users :)

Let me know if it's ok for me to create a PR

**Comment by Robby-cell** [comment]
hi @JefvdA 
I created the file, you can feel free to change it as needed and make a request!
